# Generated by Django 4.0.5 on 2022-07-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candeni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация статьи')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статья',
                'ordering': ['id'],
            },
        ),
    ]
